INSERT INTO `office_characters`.`characters` (`id`, `name`, `position`, `age`, `relationship_status`, `office_hobbies`, `quote`) VALUES
(1, 'Michael Scott', 'Gerente Regional', 45, 'Solteiro', 'Comédia improvisada; Truques de mágica', 'Isso que ela disse!'),
(2, 'Dwight Schrute', 'Assistente do Gerente Regional', 38, 'Em um relacionamento', 'Cultivo de beterrabas; Karatê', 'Roubo de identidade não é brincadeira, Jim!'),
(3, 'Jim Halpert', 'Representante de Vendas', 34, 'Casado', 'Pregar peças no Dwight; Esportes', 'Ursos. Beterrabas. Battlestar Galactica.'),
(4, 'Pam Beesly', 'Recepcionista', 32, 'Casada', 'Arte; Conversar com o Jim', 'Eu sinto Deus neste Chili''s esta noite.'),
(5, 'Angela Martin', 'Chefe de Contabilidade', 39, 'Noiva', 'Gatos; Igreja', 'Não serei chantageada por algum estreante mimado, ineficaz e afeminado de pau mole.'),
(6, 'Kevin Malone', 'Contador', 37, 'Solteiro', 'Comer; Tocar bateria', 'Por que perder tempo dizendo muito quando pouco palavra faz o trabalho?'),
(7, 'Oscar Martinez', 'Contador', 40, 'Casado', 'Debater política; Ler', 'Eu sou o único que sabe o que está acontecendo aqui.'),
(8, 'Phyllis Vance', 'Representante de Vendas', 58, 'Casada', 'Fazer tricô; Planejar festas', 'Eu sou uma mulher casada, Jim.'),
(9, 'Stanley Hudson', 'Representante de Vendas', 61, 'Casado', 'Cruzar palavras; Comer', 'Eu não sou pago para isso.'),
(10, 'Ryan Howard', 'Temporário', 28, 'Solteiro', 'Usar o celular; Ficar no Twitter', 'Eu sou o futuro.'),
(11, 'Kelly Kapoor', 'Atendimento ao Cliente', 30, 'Casada', 'Assistir reality shows; Falar sobre celebridades', 'Eu sou a maior fã do mundo.'),
(12, 'Creed Bratton', 'Controle de Qualidade', 70, 'Solteiro', 'Mentir; Comer coisas estranhas', 'Eu já fui demitido de todos os empregos que tive.'),
(13, 'Meredith Palmer', 'Representante de Relações com Fornecedores', 55, 'Solteira', 'Falar palavrões; Fumar', 'Eu não sou uma mulher fácil, mas sou uma mulher divertida.'),
(14, 'Toby Flenderson', 'Recursos Humanos', 45, 'Divorciado', 'Ler; Escrever', 'Eu sou o único que entende o que está acontecendo aqui.'),
(15, 'Ryan Howard', 'Vice-presidente de Novas Mídias', 30, 'Solteiro', 'Usar o celular; Ficar no Twitter', 'Eu sou o futuro.'),
(16, 'Darryl Philbin', 'Supervisor do Armazém', 50, 'Casado', 'Tocar baixo; Jogar basquete', 'Eu sou o único que sabe o que está acontecendo aqui.'),
(17, 'Jan Levinson', 'Vice-presidente de Vendas', 50, 'Solteira', 'Fazer compras; Planejar festas', 'Eu sou a maior fã do mundo.'),
(18, 'David Wallace', 'Diretor Financeiro', 55, 'Casado', 'Ler; Jogar golfe', 'Eu sou o único que sabe o que está acontecendo aqui.'),
(19, 'Charles Miner', 'Vice-presidente da Região Nordeste', 45, 'Casado', 'Ler; Jogar golfe', 'Eu sou o único que sabe o que está acontecendo aqui.'),
(20, 'Roy Anderson', 'Trabalhador do Armazém', 33, 'Casado', 'Beber cerveja; Jogar basquete', 'Eu sou o único que sabe o que está acontecendo aqui.'),
(21, 'Holly Flax', 'Recursos Humanos', 40, 'Casada', 'Ler; Escrever', 'Eu sou o único que entende o que está acontecendo aqui.'),
(22, 'Andy Bernard', 'Representante de Vendas', 35, 'Solteiro', 'Cantar; Tocar violão', 'Eu sou o único que sabe o que está acontecendo aqui.'),
(23, 'Erin Hannon', 'Recepcionista', 25, 'Solteira', 'Fazer compras; Falar sobre celebridades', 'Eu sou a maior fã do mundo.'),
(24, 'Nellie Bertram', 'Vice-presidente de Diversidade', 50, 'Solteira', 'Fazer compras; Planejar festas', 'Eu sou a maior fã do mundo.'),
(25, 'Robert California', 'CEO da Sabre', 55, 'Casado', 'Ler; Jogar golfe', 'Eu sou o único que sabe o que está acontecendo aqui.'),
(26, 'Jo Bennett', 'CEO da Sabre', 60, 'Casada', 'Fazer compras; Planejar festas', 'Eu sou a maior fã do mundo.'),
(27, 'Gabe Lewis', 'Diretor de Vendas da Sabre', 35, 'Solteiro', 'Ler; Jogar golfe', 'Eu sou o único que sabe o que está acontecendo aqui.'),
(28, 'Mose Schrute', 'Trabalhador na Fazenda de Beterrabas', 40, 'Solteiro', 'Cultivo de beterrabas; Karatê', 'Eu sou o único que sabe o que está acontecendo aqui.'),
(29, 'Luke', 'Sobrinho do Michael', 10, 'Solteiro', 'Jogar videogame; Comer doces', 'Eu sou o único que sabe o que está acontecendo aqui.'),
(30, 'Billy Merchant', 'Gerente de Propriedades', 50, 'Casado', 'Ler; Jogar golfe', 'Eu sou o único que sabe o que está acontecendo aqui.');
